### ISSUE TITLE
TypeError: Cannot set property '[...]' of undefined

### ISSUE THREAD

**Issue by taropaa** [donavanbecker/homebridge-platform-wemo#146]
Hi, I'm getting 

```
TypeError: Cannot set property '755d88a6-6934-45ac-a1fb-aafdf9d59418' of undefined
    at WemoPlatform.configureAccessory (/usr/local/lib/node_modules/homebridge-platform-wemo/index.js:231:38)
    at Server._configCachedPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:373:24)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:88:8)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:43:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
```

My config.json looks like this:

```
{
    "bridge": {
        "name": "Homebridge",
        "username": "AA:00:3D:E3:CE:39",
        "port": 51826,
        "pin": "999-99-999"
    },
    
    "description": "Adrian's Homebridge",

    "platforms": [
        {
            "platform": "BelkinWeMo",
            "name": "WeMo Platform",
            "homekit_safe" : "1",
            "discovery": true
        },
        {
			"platform": "Nest",
			"clientId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
			"clientSecret": "xxxxxxxxxxxxxxxxxxxxxxxx",
			"code": "xxxxxxxxxx"
		}
    ]
}
```
Wether I have the BelkinWeMo added in there or not, I am still getting that error.

**Comment by GeorgeeNico** [comment]
Seem to be getting the same issue.

**Comment by DMBlakeley** [comment]
In your config.json file the line "discovery": true is not required as this is the default.

I also do not recognize the "homekit_safe": "1" line.  I do not find in the online documentation for homebridge-platform-wemo.

May want to delete these 2 lines and see if you still have the issue.
