### ISSUE TITLE
Latest version causes Homebridge to fail

### ISSUE THREAD

**Issue by stoplis** [donavanbecker/homebridge-platform-wemo#175]
After updating to 1.5.1 this plugin stops Homebridge from loading with the following errors.

```
Error: The requested platform 'BelkinWeMo' was not registered by any plugin.
    at API.platform (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/api.js:115:19)
    at Server._loadPlatforms (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:283:47)
    at Server.run (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/server.js:74:14)
    at module.exports (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/lib/cli.js:90:12)
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/homebridge/bin/homebridge:10:63)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[Homebridge] [4/8/2020, 4:51:06 PM] Got SIGTERM, shutting down service...
```

**Comment by donavanbecker** [comment]
it has to be something with your setup, I am not experiencing this at all. Sorry

**Comment by trineu** [comment]
Here also gives the same error

**Comment by donavanbecker** [comment]
try v1.5.4

**Comment by stoplis** [comment]
v1.5.5 fixed this issue, thanks.
